<a href="https://colab.research.google.com/github/aadyasingh55/TweetDisasterPrediction/blob/main/TwitterDisasterPred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('train.csv')
df.head(10)

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
5,8,NaN,NaN,#RockyFire Update => California Hwy. 20 closed...,1
6,10,NaN,NaN,#flood #disaster Heavy rain causes flash flood...,1
7,13,NaN,NaN,I'm on top of the hill and I can see a fire in...,1
8,14,NaN,NaN,There's an emergency evacuation happening now ...,1
9,15,NaN,NaN,I'm afraid that the tornado is coming to our a...,1

In [ ]:
df.shape

(7613, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64
dtypes: int64(2), object(3)
memory usage: 297.5+ KB

In [ ]:
df.isna().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

In [ ]:
df['text'] = df['text'].str.lower()
df

,id,keyword,location,text,target
0,1,NaN,NaN,our deeds are the reason of this #earthquake m...,1
1,4,NaN,NaN,forest fire near la ronge sask. canada,1
2,5,NaN,NaN,all residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,just got sent this photo from ruby #alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @thetawniest the out of control w...,1
7610,10871,NaN,NaN,m1.94 [01:04 utc]?5km s of volcano hawaii. htt...,1
7611,10872,NaN,NaN,police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,the latest: more homes razed by northern calif...,1

In [ ]:
import re
def remove_url(text):
    return re.sub(r'http\S+', '', text)

In [ ]:
df['text'] = df['text'].apply(remove_url)

In [ ]:
df

,id,keyword,location,text,target
0,1,NaN,NaN,our deeds are the reason of this #earthquake m...,1
1,4,NaN,NaN,forest fire near la ronge sask. canada,1
2,5,NaN,NaN,all residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,just got sent this photo from ruby #alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @thetawniest the out of control w...,1
7610,10871,NaN,NaN,m1.94 [01:04 utc]?5km s of volcano hawaii.,1
7611,10872,NaN,NaN,police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,the latest: more homes razed by northern calif...,1

In [ ]:
import string
exclude = string.punctuation
def remove_punctuation(text):
    for i in exclude:
        text = text.replace(i,'')
        return text

In [ ]:
df['text'] = df['text'].apply(remove_punctuation)

In [ ]:
abbreviations = {
    "$" : " dollar ",
    "€" : " euro ",
    "4ao" : "for adults only",
    "a.m" : "before midday",
    "a3" : "anytime anywhere anyplace",
    "aamof" : "as a matter of fact",
    "acct" : "account",
    "adih" : "another day in hell",
    "afaic" : "as far as i am concerned",
    "afaict" : "as far as i can tell",
    "afaik" : "as far as i know",
    "afair" : "as far as i remember",
    "afk" : "away from keyboard",
    "app" : "application",
    "approx" : "approximately",
    "apps" : "applications",
    "asap" : "as soon as possible",
    "asl" : "age, sex, location",
    "atk" : "at the keyboard",
    "ave." : "avenue",
    "aymm" : "are you my mother",
    "ayor" : "at your own risk",
    "b&b" : "bed and breakfast",
    "b+b" : "bed and breakfast",
    "b.c" : "before christ",
    "b2b" : "business to business",
    "b2c" : "business to customer",
    "b4" : "before",
    "b4n" : "bye for now",
    "b@u" : "back at you",
    "bae" : "before anyone else",
    "bak" : "back at keyboard",
    "bbbg" : "bye bye be good",
    "bbc" : "british broadcasting corporation",
    "bbias" : "be back in a second",
    "bbl" : "be back later",
    "bbs" : "be back soon",
    "be4" : "before",
    "bfn" : "bye for now",
    "blvd" : "boulevard",
    "bout" : "about",
    "brb" : "be right back",
    "bros" : "brothers",
    "brt" : "be right there",
    "bsaaw" : "big smile and a wink",
    "btw" : "by the way",
    "bwl" : "bursting with laughter",
    "c/o" : "care of",
    "cet" : "central european time",
    "cf" : "compare",
    "cia" : "central intelligence agency",
    "csl" : "can not stop laughing",
    "cu" : "see you",
    "cul8r" : "see you later",
    "cv" : "curriculum vitae",
    "cwot" : "complete waste of time",
    "cya" : "see you",
    "cyt" : "see you tomorrow",
    "dae" : "does anyone else",
    "dbmib" : "do not bother me i am busy",
    "diy" : "do it yourself",
    "dm" : "direct message",
    "dwh" : "during work hours",
    "e123" : "easy as one two three",
    "eet" : "eastern european time",
    "eg" : "example",
    "embm" : "early morning business meeting",
    "encl" : "enclosed",
    "encl." : "enclosed",
    "etc" : "and so on",
    "faq" : "frequently asked questions",
    "fawc" : "for anyone who cares",
    "fb" : "facebook",
    "fc" : "fingers crossed",
    "fig" : "figure",
    "fimh" : "forever in my heart",
    "ft." : "feet",
    "ft" : "featuring",
    "ftl" : "for the loss",
    "ftw" : "for the win",
    "fwiw" : "for what it is worth",
    "fyi" : "for your information",
    "g9" : "genius",
    "gahoy" : "get a hold of yourself",
    "gal" : "get a life",
    "gcse" : "general certificate of secondary education",
    "gfn" : "gone for now",
    "gg" : "good game",
    "gl" : "good luck",
    "glhf" : "good luck have fun",
    "gmt" : "greenwich mean time",
    "gmta" : "great minds think alike",
    "gn" : "good night",
    "g.o.a.t" : "greatest of all time",
    "goat" : "greatest of all time",
    "goi" : "get over it",
    "gps" : "global positioning system",
    "gr8" : "great",
    "gratz" : "congratulations",
    "gyal" : "girl",
    "h&c" : "hot and cold",
    "hp" : "horsepower",
    "hr" : "hour",
    "hrh" : "his royal highness",
    "ht" : "height",
    "ibrb" : "i will be right back",
    "ic" : "i see",
    "icq" : "i seek you",
    "icymi" : "in case you missed it",
    "idc" : "i do not care",
    "idgadf" : "i do not give a damn fuck",
    "idgaf" : "i do not give a fuck",
    "idk" : "i do not know",
    "ie" : "that is",
    "i.e" : "that is",
    "ifyp" : "i feel your pain",
    "IG" : "instagram",
    "iirc" : "if i remember correctly",
    "ilu" : "i love you",
    "ily" : "i love you",
    "imho" : "in my humble opinion",
    "imo" : "in my opinion",
    "imu" : "i miss you",
    "iow" : "in other words",
    "irl" : "in real life",
    "j4f" : "just for fun",
    "jic" : "just in case",
    "jk" : "just kidding",
    "jsyk" : "just so you know",
    "l8r" : "later",
    "lb" : "pound",
    "lbs" : "pounds",
    "ldr" : "long distance relationship",
    "lmao" : "laugh my ass off",
    "lmfao" : "laugh my fucking ass off",
    "lol" : "laughing out loud",
    "ltd" : "limited",
    "ltns" : "long time no see",
    "m8" : "mate",
    "mf" : "motherfucker",
    "mfs" : "motherfuckers",
    "mfw" : "my face when",
    "mofo" : "motherfucker",
    "mph" : "miles per hour",
    "mr" : "mister",
    "mrw" : "my reaction when",
    "ms" : "miss",
    "mte" : "my thoughts exactly",
    "nagi" : "not a good idea",
    "nbc" : "national broadcasting company",
    "nbd" : "not big deal",
    "nfs" : "not for sale",
    "ngl" : "not going to lie",
    "nhs" : "national health service",
    "nrn" : "no reply necessary",
    "nsfl" : "not safe for life",
    "nsfw" : "not safe for work",
    "nth" : "nice to have",
    "nvr" : "never",
    "nyc" : "new york city",
    "oc" : "original content",
    "og" : "original",
    "ohp" : "overhead projector",
    "oic" : "oh i see",
    "omdb" : "over my dead body",
    "omg" : "oh my god",
    "omw" : "on my way",
    "p.a" : "per annum",
    "p.m" : "after midday",
    "pm" : "prime minister",
    "poc" : "people of color",
    "pov" : "point of view",
    "pp" : "pages",
    "ppl" : "people",
    "prw" : "parents are watching",
    "ps" : "postscript",
    "pt" : "point",
    "ptb" : "please text back",
    "pto" : "please turn over",
    "qpsa" : "what happens", #"que pasa",
    "ratchet" : "rude",
    "rbtl" : "read between the lines",
    "rlrt" : "real life retweet",
    "rofl" : "rolling on the floor laughing",
    "roflol" : "rolling on the floor laughing out loud",
    "rotflmao" : "rolling on the floor laughing my ass off",
    "rt" : "retweet",
    "ruok" : "are you ok",
    "sfw" : "safe for work",
    "sk8" : "skate",
    "smh" : "shake my head",
    "sq" : "square",
    "srsly" : "seriously",
    "ssdd" : "same stuff different day",
    "tbh" : "to be honest",
    "tbs" : "tablespooful",
    "tbsp" : "tablespooful",
    "tfw" : "that feeling when",
    "thks" : "thank you",
    "tho" : "though",
    "thx" : "thank you",
    "tia" : "thanks in advance",
    "til" : "today i learned",
    "tl;dr" : "too long i did not read",
    "tldr" : "too long i did not read",
    "tmb" : "tweet me back",
    "tntl" : "trying not to laugh",
    "ttyl" : "talk to you later",
    "u" : "you",
    "u2" : "you too",
    "u4e" : "yours for ever",
    "utc" : "coordinated universal time",
    "w/" : "with",
    "w/o" : "without",
    "w8" : "wait",
    "wassup" : "what is up",
    "wb" : "welcome back",
    "wtf" : "what the fuck",
    "wtg" : "way to go",
    "wtpa" : "where the party at",
    "wuf" : "where are you from",
    "wuzup" : "what is up",
    "wywh" : "wish you were here",
    "yd" : "yard",
    "ygtr" : "you got that right",
    "ynk" : "you never know",
    "zzz" : "sleeping bored and tired"
}
def convert_abbrev(word):
    return abbreviations[word.upper()] if word.lower() in abbreviations.keys() else word

In [ ]:
def remove_chatwords(df, column_name, abbreviations):
    new_texts = []
    for text in df[column_name]:
        new_text = []
        for w in text.split():
            if w.upper() in abbreviations:
                new_text.append(abbreviations[w.upper()])
            else:
                new_text.append(w)
        new_texts.append(' '.join(new_text))

    df['text'] = new_texts
    return df

In [ ]:
df = remove_chatwords(df, 'text', abbreviations)

In [ ]:
df

,id,keyword,location,text,target
0,1,NaN,NaN,our deeds are the reason of this #earthquake m...,1
1,4,NaN,NaN,forest fire near la ronge sask. canada,1
2,5,NaN,NaN,all residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,just got sent this photo from ruby #alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @thetawniest the out of control w...,1
7610,10871,NaN,NaN,m1.94 [01:04 utc]?5km s of volcano hawaii.,1
7611,10872,NaN,NaN,police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,the latest: more homes razed by northern calif...,1

In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
df['tokenized_text'] = df['text'].apply(word_tokenize)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
nltk.download('punkt')
stop_words = set(stopwords.words('english'))
def remove_stopwords(tokens):
    filtered_tokens = [token for token in tokens if token.lower() not in stop_words]
    return filtered_tokens

df['tokenized_text'] = df['tokenized_text'].apply(remove_stopwords)

print(df)

         id keyword location  \
0         1     NaN      NaN
1         4     NaN      NaN
2         5     NaN      NaN
3         6     NaN      NaN
4         7     NaN      NaN
...     ...     ...      ...
7608  10869     NaN      NaN
7609  10870     NaN      NaN
7610  10871     NaN      NaN
7611  10872     NaN      NaN
7612  10873     NaN      NaN

                                                   text  target  \
0     our deeds are the reason of this #earthquake m...       1
1                forest fire near la ronge sask. canada       1
2     all residents asked to 'shelter in place' are ...       1
3     13,000 people receive #wildfires evacuation or...       1
4     just got sent this photo from ruby #alaska as ...       1
...                                                 ...     ...
7608  two giant cranes holding a bridge collapse int...       1
7609  @aria_ahrary @thetawniest the out of control w...       1
7610         m1.94 [01:04 utc]?5km s of volcano hawaii.       1
7611  police investigating after an e-bike collided ...       1
7612  the latest: more homes razed by northern calif...       1

                                         tokenized_text
0     [deeds, reason, #, earthquake, may, allah, for...
1      [forest, fire, near, la, ronge, sask, ., canada]
2     [residents, asked, 'shelter, place, ', notifie...
3     [13,000, people, receive, #, wildfires, evacua...
4     [got, sent, photo, ruby, #, alaska, smoke, #, ...
...                                                 ...
7608  [two, giant, cranes, holding, bridge, collapse...
7609  [@, aria_ahrary, @, thetawniest, control, wild...
7610  [m1.94, [, 01:04, utc, ], ?, 5km, volcano, haw...
7611  [police, investigating, e-bike, collided, car,...
7612  [latest, :, homes, razed, northern, california...

[7613 rows x 6 columns]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def lemmatize_tokens(tokens):
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    return lemmatized_tokens

df['tokenized_text'] = df['tokenized_text'].apply(lemmatize_tokens)

print(df)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

         id keyword location  \
0         1     NaN      NaN
1         4     NaN      NaN
2         5     NaN      NaN
3         6     NaN      NaN
4         7     NaN      NaN
...     ...     ...      ...
7608  10869     NaN      NaN
7609  10870     NaN      NaN
7610  10871     NaN      NaN
7611  10872     NaN      NaN
7612  10873     NaN      NaN

                                                   text  target  \
0     our deeds are the reason of this #earthquake m...       1
1                forest fire near la ronge sask. canada       1
2     all residents asked to 'shelter in place' are ...       1
3     13,000 people receive #wildfires evacuation or...       1
4     just got sent this photo from ruby #alaska as ...       1
...                                                 ...     ...
7608  two giant cranes holding a bridge collapse int...       1
7609  @aria_ahrary @thetawniest the out of control w...       1
7610         m1.94 [01:04 utc]?5km s of volcano hawaii.       1
7611  police investigating after an e-bike collided ...       1
7612  the latest: more homes razed by northern calif...       1

                                         tokenized_text
0     [deed, reason, #, earthquake, may, allah, forg...
1      [forest, fire, near, la, ronge, sask, ., canada]
2     [resident, asked, 'shelter, place, ', notified...
3     [13,000, people, receive, #, wildfire, evacuat...
4     [got, sent, photo, ruby, #, alaska, smoke, #, ...
...                                                 ...
7608  [two, giant, crane, holding, bridge, collapse,...
7609  [@, aria_ahrary, @, thetawniest, control, wild...
7610  [m1.94, [, 01:04, utc, ], ?, 5km, volcano, haw...
7611  [police, investigating, e-bike, collided, car,...
7612  [latest, :, home, razed, northern, california,...

[7613 rows x 6 columns]

In [ ]:
df1 = pd.read_csv('test.csv')
df1.head()

   id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [ ]:
df1['text'] = df1['text'].str.lower()
df1['text'] = df1['text'].apply(remove_url)
df1['text'] = df1['text'].apply(remove_punctuation)
df1 = remove_chatwords(df1, 'text', abbreviations)
df1['tokenized_text'] = df1['text'].apply(word_tokenize)
df1['tokenized_text'] = df1['tokenized_text'].apply(remove_stopwords)
df1['tokenized_text'] = df1['tokenized_text'].apply(lemmatize_tokens)

In [ ]:
df1

,id,keyword,location,text,tokenized_text
0,0,NaN,NaN,just happened a terrible car crash,"[happened, terrible, car, crash]"
1,2,NaN,NaN,"heard about #earthquake is different cities, s...","[heard, #, earthquake, different, city, ,, sta..."
2,3,NaN,NaN,"there is a forest fire at spot pond, geese are...","[forest, fire, spot, pond, ,, goose, fleeing, ..."
3,9,NaN,NaN,apocalypse lighting. #spokane #wildfires,"[apocalypse, lighting, ., #, spokane, #, wildf..."
4,11,NaN,NaN,typhoon soudelor kills 28 in china and taiwan,"[typhoon, soudelor, kill, 28, china, taiwan]"
...,...,...,...,...,...
3258,10861,NaN,NaN,earthquake safety los angeles ûò safety faste...,"[earthquake, safety, los, angeles, ûò, safety..."
3259,10865,NaN,NaN,storm in ri worse than last hurricane. my city...,"[storm, ri, worse, last, hurricane, ., city, &..."
3260,10868,NaN,NaN,green line derailment in chicago,"[green, line, derailment, chicago]"
3261,10874,NaN,NaN,meg issues hazardous weather outlook (hwo),"[meg, issue, hazardous, weather, outlook, (, h..."
3262,10875,NaN,NaN,#cityofcalgary has activated its municipal eme...,"[#, cityofcalgary, activated, municipal, emerg..."

In [ ]:
!pip install gensim
from gensim.models import Word2Vec

Requirement already satisfied: gensim in /usr/local/lib/python3.10/dist-packages (4.3.1)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.10/dist-packages (from gensim) (1.23.5)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from gensim) (1.10.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from gensim) (6.3.0)

In [ ]:
word2vec_model1 = Word2Vec(sentences=df['tokenized_text'], vector_size=100, window=5, min_count=1, sg=0)
word2vec_model2 = Word2Vec(sentences=df1['tokenized_text'], vector_size=100, window=5, min_count=1, sg=0)

In [ ]:
word2vec_model1.save("tweet_word2vec.model1")
word2vec_model2.save("tweet_word2vec.model2")

In [ ]:
word2vec_model1 = Word2Vec.load("tweet_word2vec.model1")
word2vec_model2 = Word2Vec.load("tweet_word2vec.model2")

In [ ]:
df

,id,keyword,location,text,target,tokenized_text
0,1,NaN,NaN,our deeds are the reason of this #earthquake m...,1,"[deed, reason, #, earthquake, may, allah, forg..."
1,4,NaN,NaN,forest fire near la ronge sask. canada,1,"[forest, fire, near, la, ronge, sask, ., canada]"
2,5,NaN,NaN,all residents asked to 'shelter in place' are ...,1,"[resident, asked, 'shelter, place, ', notified..."
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1,"[13,000, people, receive, #, wildfire, evacuat..."
4,7,NaN,NaN,just got sent this photo from ruby #alaska as ...,1,"[got, sent, photo, ruby, #, alaska, smoke, #, ..."
...,...,...,...,...,...,...
7608,10869,NaN,NaN,two giant cranes holding a bridge collapse int...,1,"[two, giant, crane, holding, bridge, collapse,..."
7609,10870,NaN,NaN,@aria_ahrary @thetawniest the out of control w...,1,"[@, aria_ahrary, @, thetawniest, control, wild..."
7610,10871,NaN,NaN,m1.94 [01:04 utc]?5km s of volcano hawaii.,1,"[m1.94, [, 01:04, utc, ], ?, 5km, volcano, haw..."
7611,10872,NaN,NaN,police investigating after an e-bike collided ...,1,"[police, investigating, e-bike, collided, car,..."
7612,10873,NaN,NaN,the latest: more homes razed by northern calif...,1,"[latest, :, home, razed, northern, california,..."

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
df1.shape

(3263, 5)

In [ ]:
X_train = []

for tokens in df['tokenized_text']:
    embeddings = [word2vec_model1.wv[token] for token in tokens if token in word2vec_model1.wv]
    if embeddings:
        tweet_embedding = sum(embeddings) / len(embeddings)  # Average of word embeddings
        X_train.append(tweet_embedding)

y_train = df['target']

X_test = []

for tokens in df1['tokenized_text']:
    embeddings = [word2vec_model2.wv[token] for token in tokens if token in word2vec_model2.wv]
    if embeddings:
        tweet_embedding = sum(embeddings) / len(embeddings)  # Average of word embeddings
        X_test.append(tweet_embedding)

# Train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
# Make predictions on the test data

df1.shape

(3263, 5)

In [ ]:
y_pred.shape

(3263,)

In [ ]:
df1['target'] = y_pred
df1

,id,keyword,location,text,tokenized_text,target
0,0,NaN,NaN,just happened a terrible car crash,"[happened, terrible, car, crash]",1
1,2,NaN,NaN,"heard about #earthquake is different cities, s...","[heard, #, earthquake, different, city, ,, sta...",1
2,3,NaN,NaN,"there is a forest fire at spot pond, geese are...","[forest, fire, spot, pond, ,, goose, fleeing, ...",1
3,9,NaN,NaN,apocalypse lighting. #spokane #wildfires,"[apocalypse, lighting, ., #, spokane, #, wildf...",1
4,11,NaN,NaN,typhoon soudelor kills 28 in china and taiwan,"[typhoon, soudelor, kill, 28, china, taiwan]",0
...,...,...,...,...,...,...
3258,10861,NaN,NaN,earthquake safety los angeles ûò safety faste...,"[earthquake, safety, los, angeles, ûò, safety...",0
3259,10865,NaN,NaN,storm in ri worse than last hurricane. my city...,"[storm, ri, worse, last, hurricane, ., city, &...",1
3260,10868,NaN,NaN,green line derailment in chicago,"[green, line, derailment, chicago]",1
3261,10874,NaN,NaN,meg issues hazardous weather outlook (hwo),"[meg, issue, hazardous, weather, outlook, (, h...",1
3262,10875,NaN,NaN,#cityofcalgary has activated its municipal eme...,"[#, cityofcalgary, activated, municipal, emerg...",1

In [ ]:
data = {'id' : df1['id'] ,'target' : y_pred }
df3 = pd.DataFrame(data)
df3.to_csv('twitterdisastaer.csv', index=False)

In [ ]:
df3

         id  target
0         0       1
1         2       1
2         3       1
3         9       1
4        11       0
...     ...     ...
3258  10861       0
3259  10865       1
3260  10868       1
3261  10874       1
3262  10875       1

[3263 rows x 2 columns]